import Provider from './provider'
import { MenuBar } from './components/menuBar/menuBar'
import './globals.css'
import NavBar from './components/NavBar'

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='en'>
			<body>
				<Provider>
					{/* <MenuBar /> */}
					<NavBar />
					<div className='h-screen w-screen'>{children}</div>
				</Provider>
			</body>
		</html>
	)
}
